#!/bin/bash

# ================================================
# HTML Report Generator for Auto Pentest Script
# Converts scan output into a styled HTML report
# ================================================

TARGET=$1
RESULTS_DIR=$2
REPORT_FILE="$RESULTS_DIR/report.html"

if [[ -z "$TARGET" || -z "$RESULTS_DIR" ]]; then
  echo "Usage: $0 <target-hostname> <results-dir>"
  exit 1
fi

# HTML Header
cat > "$REPORT_FILE" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Penetration Test Report: $TARGET</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; background: #f9f9f9; color: #222; }
    h1, h2 { color: #2c3e50; }
    pre { background: #eef; padding: 10px; border-left: 4px solid #3498db; overflow-x: auto; }
    .section { margin-bottom: 40px; }
    .footer { font-size: 0.9em; color: #777; margin-top: 50px; }
  </style>
</head>
<body>
  <h1>Penetration Test Report</h1>
  <p><strong>Target:</strong> $TARGET<br>
  <strong>Date:</strong> $(date)</p>
EOF

# Helper function
add_section() {
  local title="$1"
  local file="$2"

  if [[ -f "$file" ]]; then
    echo "<div class=\"section\">" >> "$REPORT_FILE"
    echo "<h2>$title</h2>" >> "$REPORT_FILE"
    echo "<pre>" >> "$REPORT_FILE"
    cat "$file" >> "$REPORT_FILE"
    echo "</pre>" >> "$REPORT_FILE"
    echo "</div>" >> "$REPORT_FILE"
  fi
}

# Add each tool section
add_section "1. Network Scan (Nmap)" "$RESULTS_DIR/nmap.txt"
add_section "2. Web Fingerprinting (WhatWeb)" "$RESULTS_DIR/whatweb.txt"
add_section "3. Vulnerability Scan (Nikto)" "$RESULTS_DIR/nikto.txt"
add_section "4. Directory Brute-force (Gobuster)" "$RESULTS_DIR/gobuster.txt"
add_section "5. Login Brute-force (Hydra)" "$RESULTS_DIR/hydra.txt"

# SQLMap results from multiple folders
SQLMAP_DIR="$RESULTS_DIR/sqlmap"
if [[ -d "$SQLMAP_DIR" ]]; then
  echo "<div class=\"section\">" >> "$REPORT_FILE"
  echo "<h2>6. SQL Injection Testing (SQLMap)</h2>" >> "$REPORT_FILE"
  for log in "$SQLMAP_DIR"/*/log; do
    if [[ -f "$log" ]]; then
      dir=$(basename "$(dirname "$log")")
      echo "<h3>$dir</h3><pre>" >> "$REPORT_FILE"
      cat "$log" >> "$REPORT_FILE"
      echo "</pre>" >> "$REPORT_FILE"
    fi
  done
  echo "</div>" >> "$REPORT_FILE"
fi

# Recommendations
cat >> "$REPORT_FILE" <<EOF
<div class="section">
  <h2>7. Recommendations & Patching</h2>
  <ul>
    <li>Review exposed ports and services in Nmap section.</li>
    <li>Update or patch outdated software identified by WhatWeb and Nikto.</li>
    <li>Harden login forms and admin interfaces to prevent Hydra-based brute-force attacks.</li>
    <li>Fix SQL injection vulnerabilities if SQLMap found any exploitable points.</li>
    <li>Restrict access to sensitive or unintended directories found by Gobuster.</li>
  </ul>
</div>

<div class="footer">
  <p>Report generated by <code>generate_report_html.sh</code></p>
</div>

</body>
</html>
EOF

echo "[✓] HTML report generated at: $REPORT_FILE"
